[[redirects]]
  from = "/search/*"
  to = "https://api.github.com/search/:splat"
  status = 200
  force = true

  from = "/users/*"
  to = "https://api.github.com/users/:splat"
  status = 200
  force = true
